# Generated by Django 5.2.5 on 2025-08-20 09:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=5000)),
                ('source_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('spam', 'Spam')], default='new', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='core_lead_created_054771_idx'), models.Index(fields=['status'], name='core_lead_status_7318b1_idx'), models.Index(fields=['email'], name='core_lead_email_40e23f_idx')],
            },
        ),
    ]
